dist: trusty
sudo: false

language: d
os:
 - linux
 #- osx
d:
 - dmd
 #- dmd-beta
 #- dmd-nightly
 - ldc
 #- ldc-beta

addons:
  apt:
    packages:
      - pkg-config

branches:
  only:
  - master

install:
  - pyenv global system 3.6
  - pip3 install 'meson==0.47.2'
  - mkdir .ntmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
  - unzip .ntmp/ninja-linux.zip -d .ntmp

before_script:
  export PATH=$PATH:$PWD/.ntmp

script:
  - meson build && ninja -j2 -C build
  - ninja -j2 -C build test -v
  - dub build --build=release --compiler=${DC}
  - dub test --compiler=${DC}
